import type { SeedProduct } from "./seedTypes.js";

export const seedProducts: SeedProduct[] = [
  {
    slug: "custom-photo-frame",
    name: "Custom Photo Frame",
    description: "Full description of the custom photo frame with embossed name.",
    shortDescription: "Photo frame with embossed name",
    categorySlug: "gifts",
    basePrice: 4500,
    material: "PETG_HF",
    printTimeHours: 4,
    weightGrams: 120,
    status: "active",
    modelFileUrl: "/models/3d/custom-photo-frame.glb",
    thumbnailUrl: "/models/thumbnails/photo-frame.webp",
    imageUrls: [
      "/models/thumbnails/photo-frame.webp",
      "/models/thumbnails/gifts.webp",
    ],
    tags: ["gifts", "custom"],
    translations: {
      en: {
        name: "Custom Photo Frame",
        description:
          "Full description of the custom photo frame with embossed name.",
        shortDescription: "Photo frame with embossed name",
      },
      "pt-BR": {
        name: "Porta-retrato personalizado",
        description:
          "Descrição completa do porta-retrato personalizado com nome em relevo.",
        shortDescription: "Porta-retrato com nome em relevo",
      },
    },
  },
  {
    slug: "dragon-figurine",
    name: "Dragon Figurine",
    description: "Detailed dragon miniature for tabletop games.",
    shortDescription: "Tabletop dragon miniature",
    categorySlug: "miniatures",
    basePrice: 8900,
    material: "PETG_HF",
    printTimeHours: 8,
    weightGrams: 45,
    status: "active",
    modelFileUrl: null,
    thumbnailUrl: "/models/thumbnails/dragon.webp",
    imageUrls: ["/models/thumbnails/dragon.webp"],
    tags: ["miniatures", "fantasy"],
    translations: {
      en: {
        name: "Dragon Figurine",
        description: "Detailed dragon miniature for tabletop games.",
        shortDescription: "Tabletop dragon miniature",
      },
      "pt-BR": {
        name: "Miniatura de dragão",
        description: "Miniatura detalhada de dragão para jogos de mesa.",
        shortDescription: "Miniatura de dragão para RPG",
      },
    },
  },
  {
    slug: "phone-stand",
    name: "Phone Stand",
    description: "Adjustable phone stand for desk use.",
    shortDescription: "Desk phone stand",
    categorySlug: "tools",
    basePrice: 2500,
    material: "PETG_HF",
    printTimeHours: 2,
    weightGrams: 80,
    status: "active",
    modelFileUrl: null,
    thumbnailUrl: "/models/thumbnails/phone-stand.webp",
    imageUrls: [
      "/models/thumbnails/phone-stand.webp",
      "/models/thumbnails/tools.webp",
    ],
    tags: ["tools", "desk"],
    translations: {
      en: {
        name: "Phone Stand",
        description: "Adjustable phone stand for desk use.",
        shortDescription: "Desk phone stand",
      },
      "pt-BR": {
        name: "Suporte de celular",
        description: "Suporte ajustável de celular para mesa.",
        shortDescription: "Suporte de mesa para celular",
      },
    },
  },
  {
    slug: "custom-keychain",
    name: "Custom Keychain",
    description: "Personalized name keychain in durable PETG.",
    shortDescription: "Name keychain",
    categorySlug: "gifts",
    basePrice: 1500,
    material: "PETG_HF",
    printTimeHours: 1,
    weightGrams: 15,
    status: "active",
    modelFileUrl: null,
    thumbnailUrl: "/models/thumbnails/keychain.webp",
    imageUrls: ["/models/thumbnails/keychain.webp"],
    tags: ["gifts", "custom"],
    translations: {
      en: {
        name: "Custom Keychain",
        description: "Personalized name keychain in durable PETG.",
        shortDescription: "Name keychain",
      },
      "pt-BR": {
        name: "Chaveiro personalizado",
        description: "Chaveiro com nome personalizado em PETG resistente.",
        shortDescription: "Chaveiro com nome",
      },
    },
  },
  {
    slug: "planter-pot",
    name: "Planter Pot",
    description: "Geometric planter for small succulents.",
    shortDescription: "Small succulent planter",
    categorySlug: "gifts",
    basePrice: 3200,
    material: "PETG_HF",
    printTimeHours: 3,
    weightGrams: 200,
    status: "active",
    modelFileUrl: null,
    thumbnailUrl: "/models/thumbnails/planter.webp",
    imageUrls: ["/models/thumbnails/planter.webp"],
    tags: ["gifts", "home"],
    translations: {
      en: {
        name: "Planter Pot",
        description: "Geometric planter for small succulents.",
        shortDescription: "Small succulent planter",
      },
      "pt-BR": {
        name: "Vaso para plantas",
        description: "Vaso geométrico para suculentas pequenas.",
        shortDescription: "Vaso para suculentas",
      },
    },
  },
];
